name: 'Open In Notepad++ - VS Legacy'
  
on:
  push:
    tags: releases/[0-9]{1,4}+\.[0-9]{1,2}+\.[0-9]{1,2}+
    branches: master
env:
  solution: './src/CodingWithCalvin.OpenInNotepadPlusPlus.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
jobs:
  Release-Build-and-Deploy: 
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    
    - name: 1. Increment Version
      run: |
        (new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/CalvinAllen/devops-scripts/master/gh-actions-set-vsix-version.ps1") | iex
        Vsix-IncrementVersion `
            -BuildNumber ${{ github.run_number }} `
            -manifestFile './src/CodingWithCalvin.OpenInNotepadPlusPlus/source.extension.vsixmanifest' `
            -extensionSourceFile './src/CodingWithCalvin.OpenInNotepadPlusPlus/source.extension.cs'
      shell: powershell
    
    - name: 2. Bootstrapping NuGet Installer
      uses: nuget/setup-nuget@v1
    
    - name: 3. Restoring Packages
      run: nuget restore ${{ env.solution }}
    
    - name: 4. Building Solution
      run: msbuild '${{ env.solution }}' /p:configuration='${{ env.buildConfiguration }}' /p:platform='${{ env.buildPlatform }}'

    - name: 5. Copying Build Artifacts
      if: startsWith( github.ref, 'refs/tags/releases/')
      run: |
        copy '${{ github.workspace }}\src\CodingWithCalvin.OpenInNotepadPlusPlus\bin\Release\CodingWithCalvin.OpenInNotepadPlusPlus.vsix' '${{ github.workspace }}'
        copy '${{ github.workspace }}\extension.manifest.json' '${{ github.workspace }}'
        copy '${{ github.workspace }}\README.me' '${{ github.workspace }}'
        
    - name: 6. Publish Release to Marketplace
      if: startsWith( github.ref, 'refs/tags/releases/')
      uses: cezarypiatek/VsixPublisherAction@0.2
      with:
         extension-file: '${{ github.workspace }}/CodingWithCalvin.OpenInNotepadPlusPlus.vsix'
         publish-manifest-file: '${{ github.workspace }}/extension.manifest.json'
         personal-access-code: '${{ secrets.VS_MARKETPLACE_PAT }}'             
